# Generated by Django 5.0.7 on 2024-08-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="platform",
            name="abbreviation",
            field=models.CharField(default="N/A", max_length=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/infrastructure/"
            ),
        ),
    ]
