# Generated by Django 5.0.7 on 2024-08-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentation", "0002_category_product_delete_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="abbreviation",
            field=models.CharField(default="UNKNOWN", max_length=10),
            preserve_default=False,
        ),
    ]
