# Generated by Django 5.0.7 on 2024-08-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentation", "0002_platform_abbreviation_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="infrastructure/"),
        ),
    ]
