# Generated by Django 5.0.7 on 2024-08-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentation", "0003_category_abbreviation"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="platform",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
