# Generated by Django 3.1.2 on 2024-08-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentation', '0003_category_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
