# Generated by Django 5.0.7 on 2024-08-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentation", "0004_platform_category_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="platform",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name="Platform",
        ),
    ]
