# Generated by Django 5.0.7 on 2024-08-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentation", "0004_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
