<<<<<<< HEAD
# Generated by Django 3.1.2 on 2024-08-06 09:24
=======
# Generated by Django 5.0.7 on 2024-08-06 08:50
>>>>>>> a4c9d630d0a7ade70c46d0961c35bb76e279776a

from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
=======
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.TextField()),
>>>>>>> a4c9d630d0a7ade70c46d0961c35bb76e279776a
            ],
        ),
    ]
