# Generated by Django 5.0.7 on 2024-08-06 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_contact_sent_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="subject",
            new_name="message",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="sent_at",
        ),
    ]
