# Generated by Django 3.1.2 on 2024-08-06 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='sent_at',
        ),
    ]
