# Generated by Django 5.0.7 on 2024-08-07 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_contact_sent_at'),
        ('contact', '0003_rename_subject_contact_message_and_more'),
    ]

    operations = [
    ]
